name: Rachid
author: Rachid al Maach
baseurl:
description: Emptying my mind
github: http://www.github.com/rachid
twitter: http://www.twitter.com/rachidalm
linkedin: https://nl.linkedin.com/in/rachidalmaach

email: rachid[at]qraft.nl
location: 42°2'16"N   70°12'47"W
disqus: rachidgithubio

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
